### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by ccfontes** [tessellator/bell#1]
Hi @tessellator long time no speak :)

This is more of a general feedback about using this awesome library, rather than dedicated issue:

- bell's zero deps was a [perfect match](https://github.com/ccfontes/faas-bb/blob/main/examples/http/bb-routes-bell/handler.clj) to showcase using [faas-bb](https://github.com/ccfontes/faas-bb) to build an API.
- it's hard to find bell, because the repo isn't setup with keywords
- would you consider babashka certifying this project using a [badge](https://github.com/babashka/babashka#badges)?

**Comment by tessellator** [comment]
Hey @ccfontes - it's great to hear from you! I am glad you have found this library useful. :)

Thank you so much for your feedback. I have added a number of keywords to the repo and the Babashka compatibility badge to the readme.

Your OpenFaaS template looks really cool! I'll have to give it a spin soon.

Thanks!
